# Generated by Django 5.1.1 on 2024-10-26 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0002_rename_notification_value_notification_notification_val",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="friend_id",
            new_name="friendname",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="user_id",
            new_name="username",
        ),
    ]
