# Generated by Django 5.1.1 on 2024-10-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0004_alter_message_friendname"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
