POST http://127.0.0.1:8000/signin/
Content-Type: application/json

{
    "email": "jamwalmansi16@gmail.com",
    "password": "mansi123"
}


# POST http://127.0.0.1:8000/signup
# Content-Type: application/json

# {
#     "username": "zack",
#     "password": "Pass1234!",
#     "email": "zack@gmail.com"
# }

# GET http://127.0.0.1:8000/test_token
# Content-Type: application/json
# Authorization: Token 5d3f481b67e6789cd8e8f2d141dd8e241181006b

# {}