# POST http://127.0.0.1:8000/signin/
# Content-Type: application/json

# {
#     "email": "jamwalmansi16@gmail.com",
#     "password": "mansi123"
# }


# POST http://127.0.0.1:8000/signup
# Content-Type: application/json

# {
#     "username": "zack",
#     "password": "Pass1234!",
#     "email": "zack@gmail.com"
# }

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 47a20d1255bf392f835afb38a87b8a5b73441ace

{}